sonar.projectKey=ura_ia_1972
sonar.organization=ramonesnaola

sonar.sources=.
sonar.exclusions=**/tests/**,**/backups/**,**/data/**,**/logs/**,**/venv/**,**/__pycache__/**,**/.venv/**,**/archive/**,**/scripts/GX10/**,**/scripts/manual_tests/**,**/scripts/legacy/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.bandit.reportPaths=bandit-report.json
