"""Chaos tests: validación de escenarios extremos del pipeline."""
from __future__ import annotations

import os
import subprocess
import time
from pathlib import Path
from unittest import mock

import pytest

from scripts.pro.tuneladora.config import Configuration
from scripts.pro.tuneladora.pipeline.runner import PipelineRunner
from scripts.pro.tuneladora.pipeline.tools.base import Status
from scripts.pro.tuneladora.pipeline.tools.bandit_tool import BanditTool
from scripts.pro.tuneladora.pipeline.tools.ruff_tool import RuffTool


@pytest.fixture
def cfg() -> Configuration:
    return Configuration()


class TestChaosSyntaxError:
    def test_syntax_error_aborts(self, cfg):
        bad = Path("/tmp/test_chaos_syntax.py")
        bad.write_text("def foo(\n")
        runner = PipelineRunner(cfg, mode="gate", files=[str(bad)])
        result = runner._run_py_compile()
        bad.unlink(missing_ok=True)
        assert result.status == Status.FAIL


class TestChaosBlastRadius:
    def test_blast_radius_blocks(self, cfg):
        runner = PipelineRunner(cfg, mode="gate", files=[f"f{i}.py" for i in range(51)])
        with mock.patch("subprocess.run") as mock_run:
            mock_run.return_value = mock.Mock(
                returncode=0, stdout="\n".join(f"f{i}.py" for i in range(51)),
                stderr="", spec=["returncode", "stdout", "stderr"],
            )
            results = runner.phase_integrity()
        assert any(r.name == "blast_radius" and r.status == Status.FAIL for r in results)


class TestChaosRollbackCreated:
    def test_rollback_deletes_created_file(self, tmp_path):
        snap_dir = tmp_path / ".tuneladora_chaos"
        snap_dir.mkdir()
        from scripts.pro.tuneladora.pipeline.snapshot_manager import SnapshotManager
        sm = SnapshotManager(snap_dir)

        existing = tmp_path / "existing.py"
        existing.write_text("x = 1\n")

        snap_path = sm.take("chaos_test", [existing])
        # Now simulate that a new file was created by the IA
        snapshot_meta_dir = snap_path
        # The snapshot didn't capture the new file (it didn't exist at take time)
        # Simulate rollback: new file was added to meta as "created_file"
        import json
        meta = json.loads((snap_path / "meta.json").read_text())
        meta["created_files"] = [str(tmp_path / "ia_created.py")]
        (snap_path / "meta.json").write_text(json.dumps(meta))

        # Create the IA-generated file
        ia_file = tmp_path / "ia_created.py"
        ia_file.write_text("# generated by IA\n")
        assert ia_file.exists()

        sm.restore(snap_path)
        assert not ia_file.exists()
        assert existing.read_text() == "x = 1\n"

    def test_restore_only_deletes_tracked_files(self, tmp_path):
        snap_dir = tmp_path / ".tuneladora_chaos2"
        snap_dir.mkdir()
        from scripts.pro.tuneladora.pipeline.snapshot_manager import SnapshotManager
        sm = SnapshotManager(snap_dir)

        existing = tmp_path / "keep.py"
        existing.write_text("keep\n")
        untracked = tmp_path / "untracked.py"
        untracked.write_text("untracked\n")

        snap = sm.take("chaos_test2", [existing])
        sm.restore(snap)
        assert untracked.exists()  # untracked file should survive


class TestChaosTestManipulation:
    def test_detects_test_manipulation(self, cfg):
        runner = PipelineRunner(cfg, mode="check", files=["src.py", "test_src.py"])
        with mock.patch("subprocess.run") as mock_run:
            mock_run.return_value = mock.Mock(
                returncode=0, stdout="src.py\ntest_src.py",
                stderr="", spec=["returncode", "stdout", "stderr"],
            )
            results = runner.phase_integrity()
        assert any(r.name == "test_manipulation" and r.status == Status.WARN for r in results)

    def test_skips_when_only_source(self, cfg):
        runner = PipelineRunner(cfg, mode="check", files=["src.py"])
        with mock.patch("subprocess.run") as mock_run:
            mock_run.return_value = mock.Mock(
                returncode=0, stdout="src.py",
                stderr="", spec=["returncode", "stdout", "stderr"],
            )
            results = runner.phase_integrity()
        assert not any(r.name == "test_manipulation" for r in results)

    def test_skips_when_only_tests(self, cfg):
        runner = PipelineRunner(cfg, mode="check", files=["test_src.py"])
        with mock.patch("subprocess.run") as mock_run:
            mock_run.return_value = mock.Mock(
                returncode=0, stdout="test_src.py",
                stderr="", spec=["returncode", "stdout", "stderr"],
            )
            results = runner.phase_integrity()
        assert not any(r.name == "test_manipulation" for r in results)


class TestChaosLock:
    def test_lock_prevents_concurrent(self, tmp_path):
        from scripts.pro.tuneladora.config import Configuration as Cfg
        c = Cfg()
        c.tuneladora_dir = tmp_path / ".tuneladora"
        c.tuneladora_dir.mkdir()
        runner = PipelineRunner(c, mode="check")
        assert runner._acquire_lock()
        runner2 = PipelineRunner(c, mode="check")
        assert not runner2._acquire_lock()
        runner._release_lock()
        assert runner2._acquire_lock()
        runner2._release_lock()

    def test_lock_cleanup(self, tmp_path):
        from scripts.pro.tuneladora.config import Configuration as Cfg
        c = Cfg()
        c.tuneladora_dir = tmp_path / ".tuneladora"
        c.tuneladora_dir.mkdir()
        runner = PipelineRunner(c, mode="check")
        assert runner._acquire_lock()
        runner._release_lock()
        runner2 = PipelineRunner(c, mode="check")
        assert runner2._acquire_lock()
        runner2._release_lock()

    def test_stale_lock_overwritten(self, tmp_path):
        from scripts.pro.tuneladora.config import Configuration as Cfg
        c = Cfg()
        c.tuneladora_dir = tmp_path / ".tuneladora"
        c.tuneladora_dir.mkdir()
        lock_path = c.tuneladora_dir / "pipeline.lock"
        import json as _json
        lock_path.write_text(_json.dumps({"pid": 0, "start": 0}))
        os.utime(str(lock_path), (time.time() - 3600, time.time() - 3600))
        runner = PipelineRunner(c, mode="check")
        assert runner._acquire_lock()
        runner._release_lock()


class TestChaosCleanCommit:
    def test_gate_commits_clean_changes(self, cfg, tmp_path):
        src = tmp_path / "clean.py"
        src.write_text("x = 1\n")
        runner = PipelineRunner(cfg, mode="gate", files=[str(src)])
        runner.sofia = mock.Mock()
        runner.sofia.review.return_value = mock.Mock(
            hallazgos=[], n_criticos=0, n_advertencias=0,
        )
        with mock.patch.multiple(
            runner, preflight=mock.DEFAULT, phase_snapshot=mock.DEFAULT,
            phase_static=mock.DEFAULT, phase_dynamic=mock.DEFAULT,
            phase_api_diff=mock.DEFAULT, phase_index=mock.DEFAULT,
            phase_integrity=mock.DEFAULT, phase_verdict=mock.DEFAULT,
            _acquire_lock=mock.DEFAULT, _release_lock=mock.DEFAULT,
        ):
            runner.preflight.return_value = [mock.Mock(name="pre", status=Status.OK)]
            runner.phase_snapshot.return_value = [mock.Mock(name="snap", status=Status.OK)]
            runner.phase_static.return_value = [mock.Mock(name="static", status=Status.OK)]
            runner.phase_dynamic.return_value = [mock.Mock(name="dynamic", status=Status.OK)]
            runner.phase_api_diff.return_value = [mock.Mock(name="api", status=Status.OK)]
            runner.phase_index.return_value = [mock.Mock(name="idx", status=Status.OK)]
            runner.phase_integrity.return_value = [mock.Mock(name="integrity", status=Status.OK)]
            runner.phase_verdict.return_value = (Status.OK, "all good")
            runner._acquire_lock.return_value = True
            result = runner.run()
        assert result == Status.OK


class TestChaosAPIDiff:
    def test_detects_new_function(self, tmp_path, cfg):
        src = tmp_path / "api_test.py"
        src.write_text("def new_func(): pass\n")
        runner = PipelineRunner(cfg, mode="check", files=[str(src)])
        with mock.patch("subprocess.run") as mock_run:
            mock_run.return_value = mock.Mock(
                returncode=128, stdout="", stderr="fatal: path not found",
                spec=["returncode", "stdout", "stderr"],
            )
            results = runner.phase_api_diff()
        assert any(r.name == "api_diff" for r in results)

    def test_empty_when_no_git_history(self, tmp_path, cfg):
        src = tmp_path / "api_test_new.py"
        src.write_text("x = 1\n")
        runner = PipelineRunner(cfg, mode="check", files=[str(src)])
        results = runner.phase_api_diff()
        assert any(r.status == Status.OK for r in results)
