#!/bin/bash
echo "═══════════════════════════════════════"
echo "  MÁQUINAS URA — Nombres normalizados"
echo "═══════════════════════════════════════"
echo ""
echo "  ⚠️  GX10 = ASUS X10 — ES LA MISMA MÁQUINA"
echo ""
echo "  GX10 (ASUS X10)"
echo "    Tailscale: gx10-64c3 (10.164.1.99)"
echo "    Thunderbolt: 10.164.1.10"
echo "    Red local: 192.168.1.135"
echo "    OS: Linux"
echo "    Rol: Única máquina — Ollama, Pro, Thunderbolt"
echo ""
echo "  Mac Mini de Ramón"
echo "    Tailscale: mac-mini-de-ramon (100.123.81.101)"
echo "    Thunderbolt: 10.164.1.17"
echo "    Red local: 10.164.1.26"
echo "    OS: macOS"
echo "    Rol: Desarrollo, Dashboard, Registry"
echo ""
echo "  caja0"
echo "    Tailscale: caja0 (100.127.217.113)"
echo "    OS: Windows"
echo "    Rol: No forma parte de URA"
echo "═══════════════════════════════════════"
