apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ura-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramon-kaixo/ura-ai
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ura
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ura-project
  namespace: argocd
spec:
  description: URA GitOps Project
  sourceRepos:
  - https://github.com/ramon-kaixo/ura-ai
  destinations:
  - namespace: ura
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
