apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: ura-service-profile
  namespace: ura
spec:
  selector:
    app: ura
  routes:
  - name: chat
    condition:
      method: POST
      pathRegex: /v2/chat
  - name: health
    condition:
      method: GET
      pathRegex: /v2/health
  retryBudget:
    retryRatio: 0.2
    percentiles:
    - 50
    - 90
    - 99
  timeoutPolicy:
    requestTimeout: 5s
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerPolicy
metadata:
  name: ura-server-policy
  namespace: ura
spec:
  selector:
    app: ura
  identity:
    - issuer: linkerd.io
  ports:
  - port: 8000
    proxyProtocol: HTTP/2
