apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedCluster
metadata:
  name: ura-prod
  labels:
    env: production
spec:
  hubAcceptsClient: true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedCluster
metadata:
  name: ura-staging
  labels:
    env: staging
spec:
  hubAcceptsClient: true
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ura-subscription
  namespace: ura
spec:
  channel: ura-channel
  name: ura-app
  placement:
    clusters:
    - name: ura-prod
    - name: ura-staging
