"""Rutas absolutas de binarios del sistema para subprocess seguros."""
import shutil

BASH = shutil.which("bash") or "/usr/bin/bash"
DOCKER = shutil.which("docker") or "/usr/bin/docker"
GIT = shutil.which("git") or "/usr/bin/git"
KILL = shutil.which("kill") or "/usr/bin/kill"
OPEN = shutil.which("open") or "/usr/bin/open"
OSASCRIPT = shutil.which("osascript") or "/usr/bin/osascript"
PGREP = shutil.which("pgrep") or "/usr/bin/pgrep"
PKILL = shutil.which("pkill") or "/usr/bin/pkill"
PS = shutil.which("ps") or "/usr/bin/ps"
PYTHON = shutil.which("python3") or "/usr/bin/python3"
RM = shutil.which("rm") or "/usr/bin/rm"
RUFF = shutil.which("ruff") or shutil.which("ruff") or "/usr/local/bin/ruff"
SCP = shutil.which("scp") or "/usr/bin/scp"
SCRIPT = shutil.which("script") or "/usr/bin/script"
SCROT = shutil.which("scrot") or "/usr/bin/scrot"
SSH = shutil.which("ssh") or "/usr/bin/ssh"
SYSTEMCTL = shutil.which("systemctl") or "/usr/bin/systemctl"
TAILSCALE = shutil.which("tailscale") or "/usr/bin/tailscale"
UPTIME = shutil.which("uptime") or "/usr/bin/uptime"
XDOTOOL = shutil.which("xdotool") or "/usr/bin/xdotool"
