streams:
  barra1_main: rtsp://admin:admin@192.168.1.101:554/cam/realmonitor?channel=1&subtype=0
  barra1_sub:  rtsp://admin:admin@192.168.1.101:554/cam/realmonitor?channel=1&subtype=1
  barra2_main: rtsp://admin:admin@192.168.1.102:554/cam/realmonitor?channel=1&subtype=0
  barra2_sub:  rtsp://admin:admin@192.168.1.102:554/cam/realmonitor?channel=1&subtype=1
  cocina1_main: rtsp://admin:admin@192.168.1.103:554/cam/realmonitor?channel=1&subtype=0
  cocina1_sub:  rtsp://admin:admin@192.168.1.103:554/cam/realmonitor?channel=1&subtype=1
  entrada1_main: rtsp://admin:admin@192.168.1.104:554/cam/realmonitor?channel=1&subtype=0
  entrada1_sub:  rtsp://admin:admin@192.168.1.104:554/cam/realmonitor?channel=1&subtype=1
  terraza1_main: rtsp://admin:admin@192.168.1.105:554/cam/realmonitor?channel=1&subtype=0
  terraza1_sub:  rtsp://admin:admin@192.168.1.105:554/cam/realmonitor?channel=1&subtype=1
  barra3_main: rtsp://admin:admin@192.168.2.101:554/cam/realmonitor?channel=1&subtype=0
  barra3_sub:  rtsp://admin:admin@192.168.2.101:554/cam/realmonitor?channel=1&subtype=1
  barra4_main: rtsp://admin:admin@192.168.2.102:554/cam/realmonitor?channel=1&subtype=0
  barra4_sub:  rtsp://admin:admin@192.168.2.102:554/cam/realmonitor?channel=1&subtype=1
  cocina2_main: rtsp://admin:admin@192.168.2.103:554/cam/realmonitor?channel=1&subtype=0
  cocina2_sub:  rtsp://admin:admin@192.168.2.103:554/cam/realmonitor?channel=1&subtype=1
  entrada2_main: rtsp://admin:admin@192.168.2.104:554/cam/realmonitor?channel=1&subtype=0
  entrada2_sub:  rtsp://admin:admin@192.168.2.104:554/cam/realmonitor?channel=1&subtype=1
  terraza2_main: rtsp://admin:admin@192.168.2.105:554/cam/realmonitor?channel=1&subtype=0
  terraza2_sub:  rtsp://admin:admin@192.168.2.105:554/cam/realmonitor?channel=1&subtype=1
  barra5_main: rtsp://admin:admin@192.168.3.101:554/cam/realmonitor?channel=1&subtype=0
  barra5_sub:  rtsp://admin:admin@192.168.3.101:554/cam/realmonitor?channel=1&subtype=1
  cocina3_main: rtsp://admin:admin@192.168.3.102:554/cam/realmonitor?channel=1&subtype=0
  cocina3_sub:  rtsp://admin:admin@192.168.3.102:554/cam/realmonitor?channel=1&subtype=1
  entrada3_main: rtsp://admin:admin@192.168.3.103:554/cam/realmonitor?channel=1&subtype=0
  entrada3_sub:  rtsp://admin:admin@192.168.3.103:554/cam/realmonitor?channel=1&subtype=1
  almacen_main: rtsp://admin:admin@192.168.3.104:554/cam/realmonitor?channel=1&subtype=0
  almacen_sub:  rtsp://admin:admin@192.168.3.104:554/cam/realmonitor?channel=1&subtype=1
  exterior_main: rtsp://admin:admin@192.168.3.105:554/cam/realmonitor?channel=1&subtype=0
  exterior_sub:  rtsp://admin:admin@192.168.3.105:554/cam/realmonitor?channel=1&subtype=1
