services:
  monitor-visual:
    image: jlesage/baseimage-gui:ubuntu-22.04-v4
    container_name: ura_monitor_visual
    ports:
      - "5800:5800"
    environment:
      - APP_NAME=URA Visual Monitor
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=720
      - DISPLAY_DEPTH=24
      - VNC_PASSWORD=ura2026
    shm_size: 2gb
    restart: unless-stopped
