#!/bin/bash
set -euo pipefail
echo "═══════════════════════════════════════"
echo "  PLAN B — RECUPERACIÓN Y MANTENIMIENTO"
echo "═══════════════════════════════════════"
echo ""
echo "1. Health Check"
bash "$(dirname "$0")/health_check.sh"
echo ""
echo "2. Backup de emergencia"
bash "$(dirname "$0")/emergency_backup.sh"
echo ""
echo "3. Modo bare-metal (análisis sin Docker)"
bash "$(dirname "$0")/bare_metal.sh"
echo ""
echo "═══════════════════════════════════════"
echo "  PLAN B COMPLETADO"
echo "═══════════════════════════════════════"
