# Override to use nvidia-spark Avahi config (avahi-daemon-dgx-spark.conf).
# Managed by the nvidia-spark-avahi-conf package.

[Service]
ExecStart=
ExecStart=/usr/sbin/avahi-daemon -s -f /etc/avahi/avahi-daemon-dgx-spark.conf
ExecReload=
ExecReload=/usr/sbin/avahi-daemon -r -f /etc/avahi/avahi-daemon-dgx-spark.conf
